apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp2-api
  namespace: vitornogueira
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp2-api
  template:
    metadata:
      labels:
        app: tp2-api
    spec:
      containers:
        - name: api
          image: docker.io/fagundes1500/tp2-api:0.2
          env:
            - name: MODEL_DIR
              value: /mnt/shared
            - name: MODEL_FILE
              value: model_rules.pkl
            - name: IMAGE_TAG
              value: "0.2"
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: shared
              mountPath: /mnt/shared
      volumes:
        - name: shared
          persistentVolumeClaim:
            claimName: project2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tp2-api-svc
  namespace: vitornogueira
spec:
  type: ClusterIP
  selector:
    app: tp2-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
# Service para acesso externo (NodePort = 50032)
apiVersion: v1
kind: Service
metadata:
  name: tp2-api-nodeport
  namespace: vitornogueira
spec:
  type: NodePort
  selector:
    app: tp2-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 50032

