apiVersion: v1
kind: Pod
metadata:
  name: pod-list
  namespace: vitornogueira
spec:
  restartPolicy: Never
  volumes:
    - name: shared
      persistentVolumeClaim:
        claimName: project2-pvc
  containers:
    - name: lister
      image: busybox:1.36
      command: ["sh","-c","ls -lh /mnt/shared"]
      volumeMounts:
        - name: shared
          mountPath: /mnt/shared
